
services:
  db:
    image: postgres:15-alpine
    container_name: restaurante_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: restaurante
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: .
    container_name: restaurante_backend
    environment:
      - DATABASE_URL=postgresql://admin:password@db:5432/restaurante
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/.venv

volumes:
  postgres_data:
